FROM nginx:1.19.4

COPY src /usr/share/nginx/html


ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["nginx", "-g", "daemon off;"]

/docker-entrypoint.sh nginx -g daemon off;


nginx -g daemon off;

"$@"


PID 1
