version: "3.8"

services:
  db-mysql:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql/data
      - ./app.py:/app/app.py
    environment:
      MYSQL_ROOT_PASSWORD: MYPASS
  nginx:
    image: nginx:1.19
    ports:
      - 8080:80
  app:
    build:
      context: .
    image: nachomillangarcia/my-flask
    
volumes:
  db-data:

