version: "3.8"

services:
  db:
    image: postgres:12.2
    environment:
      POSTGRES_USER: test
      POSTGRES_DB: test
      POSTGRES_PASSWORD: test
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80     
    depends_on:
      - myweb
  myweb:
    build:
      context: .
    image: nachomillangarcia/ejercicio
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://test:test@db:5432/test
    depends_on:
      - db

volumes:
  pgdata: